---
version: '3.7'

#volumes:
    #prometheus_data: {}
    #grafana_data: {}

########################################################################################
# Prometheus
# https://prometheus.io/
# https://quay.io/repository/prometheus/prometheus
########################################################################################

services:

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    container_name: prometheus
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/prometheus:/etc/prometheus
      - ${VOLUME_DIR}/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      #- cadvisor:cadvisor
      - alertmanager:alertmanager
    #depends_on:
      #- cadvisor
    #networks:
      #- traefik_proxy
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    #networks:
      #- back-tier
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    container_name: alertmanager
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9093:9093
    volumes:
      - ${DOCKER_DIR}/alertmanager/:/etc/alertmanager/
    #networks:
      #- back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}

  #cadvisor:
    #image: google/cadvisor
    #volumes:
      #- /:/rootfs:ro
      #- /var/run:/var/run:rw
      #- /sys:/sys:ro
      #- /var/lib/docker/:/var/lib/docker:ro
    #ports:
      #- 8080:8080
    #networks:
      #- back-tier
    #restart: always
    #deploy:
      #mode: global

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ${VOLUME_DIR}/grafana:/var/lib/grafana
      - ${DOCKER_DIR}/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - traefik_proxy
    restart: always

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge