---
version: "2"
services:

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    domainname: docker
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      # - '67:67/udp'
      #- 'XXXX:80'
      #- 'YYYY:443'
    restart: unless-stopped
    volumes:
      - /home/pi/containers/config/pihole/pihole:/etc/pihole
      - /home/pi/containers/config/pihole/pihole.log:/var/log/pihole.log
      - /home/pi/containers/config/pihole/dnsmask.d:/etc/dnsmasq.d
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    environment:
      #- ServerIP=${SERVER_IP}
      - PROXY_LOCATION=pihole
      #- VIRTUAL_HOST=pihole.${DOMAINNAME}
      #- VIRTUAL_PORT=80
      - TZ=America/Los_Angeles
      #- WEBPASSWORD=RandomWhenCommentedOut
      - DNS1=127.0.0.1
      - DNS2=1.1.1.1
      #- DNS2=1.0.0.1
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pihole"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      #- "traefik.frontend.rule=HostRegexp:pihole.${DOMAINNAME},{catchall:.*}"
      - "traefik.frontend.rule=Host:***REMOVED***.duckdns.org; PathPrefixStrip: /pihole"
      - "traefik.frontend.priority=1"
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=duckdns.org
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true