loglevel = "ERROR"

[backends]
  [backends.backend-cockpit-pi]
    [backends.backend-cockpit-pi.servers]
      [backends.backend-cockpit-pi.servers.server-cockpit-pi-ext]
        url = "http://192.168.1.50:9090"
        weight = 0
  [backends.backend-cockpit-pc]
    [backends.backend-cockpit-pc.servers]
      [backends.backend-cockpit-pc.servers.server-cockpit-pc-ext]
        url = "http://192.168.1.55:9090"
        weight = 0
  [backends.backend-plex]
    [backends.backend-plex.servers]
      [backends.backend-plex.servers.server-plex-ext]
        url = "http://192.168.1.50:32400/web/index.html"
        weight = 0
  [backends.backend-netgear]
    [backends.backend-netgear.servers]
      [backends.backend-netgear.servers.server-netgear-ext]
        url = "http://192.168.1.1"
        weight = 0
  [backends.backend-guacamole]
    [backends.backend-guacamole.servers]
      [backends.backend-guacamole.servers.server-guacamole-ext]
        url = "http://192.168.1.55:8080"
        weight = 0
  [backends.backend-freeipa]
    [backends.backend-freeipa.servers]
      [backends.backend-freeipa.servers.server-freeipa-ext]
        url = "https://192.168.1.55:443"
        weight = 0

[frontends]
  [frontends.frontend-cockpit-pi]
    backend = "backend-cockpit-pi"
    passHostHeader = true
    [frontends.frontend-cockpit-pi.routes]
        [frontends.frontend-cockpit-pi.routes.route-cockpit-pi-ext]
            rule = "Host:cockpit-pi.***INSERT_FQDN***"
  [frontends.frontend-cockpit-pc]
    backend = "backend-cockpit-pc"
    passHostHeader = true
    [frontends.frontend-cockpit-pc.routes]
        [frontends.frontend-cockpit-pc.routes.route-cockpit-pc-ext]
            rule = "Host:cockpit-pc.***INSERT_FQDN***"
  [frontends.frontend-plex]
    backend = "backend-plex"
    passHostHeader = true
    [frontends.frontend-plex.routes]
        [frontends.frontend-plex.routes.route-plex-ext]
            rule = "Host:plex.***INSERT_FQDN***"
  [frontends.frontend-netgear]
    backend = "backend-netgear"
    passHostHeader = true
    [frontends.frontend-netgear.routes]
        [frontends.frontend-netgear.routes.route-netgear-ext]
            rule = "Host:netgear.***INSERT_FQDN***"
  [frontends.frontend-guacamole]
    backend = "backend-guacamole"
    passHostHeader = true
    [frontends.frontend-guacamole.routes]
        [frontends.frontend-guacamole.routes.route-guacamole-ext]
            rule = "Host:guacamole.***INSERT_FQDN***;AddPrefix:/guacamole"
  [frontends.frontend-freeipa]
    backend = "backend-freeipa"
    passHostHeader = true
    [frontends.frontend-freeipa.routes]
        [frontends.frontend-freeipa.routes.route-freeipa-ext]
            rule = "Host:ipa.***INSERT_FQDN***"

