#https://hub.docker.com/r/netdata/netdata
version: '2'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: ***REMOVED***.duckdns.org # set to fqdn of host
    environment:
      - PUID=1000
      - PGID=1000
      - PGID=996
    #ports:
      #- 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=netdata"
      #- "traefik.frontend.rule=Host:erikpi3-netdata.duckdns.org; PathPrefixStrip: /netdata"
      - "traefik.frontend.rule=Host:netdata.***REMOVED***.duckdns.org"
      - "traefik.port=19999"
      #- "traefik.protocol=https"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.basic.users=***REMOVED***:$$apr1$$UNjtB1lq$$5hLoTdGN.M9RXlEMbkwZf0"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy