---
version: "3"
services:

  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${MYSQL_PASSWORD} # Had trouble with this. May not support password with special characters?
      - DB_DATABASE=bookstackapp
      - APP_URL=https://bookstack.${FQDN}
    volumes:
      - ${CONFIG_DIR}/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    networks:
        - backend
    depends_on:
      - bookstack_db
    labels:
    - "traefik.enable=true"
    - "traefik.backend=bookstack"
    - "traefik.frontend.rule=Host:bookstack.${FQDN}"
    - "traefik.port=80"
    - "traefik.docker.network=backend"
    - "traefik.frontend.headers.SSLRedirect=true"
    - "traefik.frontend.headers.STSSeconds=315360000"
    - "traefik.frontend.headers.browserXSSFilter=true"
    - "traefik.frontend.headers.contentTypeNosniff=true"
    - "traefik.frontend.headers.forceSTSHeader=true"
    - "traefik.frontend.headers.SSLHost=example.com"
    - "traefik.frontend.headers.STSIncludeSubdomains=true"
    - "traefik.frontend.headers.STSPreload=true"
    - "traefik.frontend.headers.frameDeny=true"

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${CONFIG_DIR}/bookstackdb:/config
    restart: unless-stopped
    networks:
        - backend

  # bookstack_db:
  #   image: mariadb:latest # There is no armv7 image available from MariaDB
  #   container_name: bookstack_db
  #   # command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
  #   restart: unless-stopped
  #   volumes:
  #     - ${CONFIG_DIR}/bookstackdb:/config
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_DATABASE=bookstackapp
  #     - MYSQL_USER=bookstack

networks:
  backend:
    external:
      name: backend
      #run: docker network create --name=backend