---
version: "2"
services:

volumes:
  portainer_data2:
    driver: local

  portainer2:
    image: portainer/portainer
    container_name: portainer2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
#    ports:
#        - "XXXX:9000"
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer2"
      - "traefik.frontend.rule=Host:***REMOVED***.duckdns.org; PathPrefix: /portainer2"
#      - "traefik.frontend.rule=Host:sonarr.${DOMAINNAME}"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"