---
version: '3.7'
services:

########################################################################################
# Gotify
# https://gotify.net/docs/config
########################################################################################

  gotify:
    image: gotify/server-arm7
    container_name: gotify
    restart: unless-stopped
    volumes:
        - ${CONFIG_DIR}/gotify:/app/data
    environment:
        - GOTIFY_SERVER_PORT=80
        #- GOTIFY_SERVER_LISTENADDR=
        - GOTIFY_SERVER_SSL_ENABLED=false
        - GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=true
        #- GOTIFY_SERVER_SSL_LISTENADDR=
        - GOTIFY_SERVER_SSL_PORT=443
        #- GOTIFY_SERVER_SSL_CERTFILE=
        #- GOTIFY_SERVER_SSL_CERTKEY=
        #- GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED=false
        #- GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS=false
        #- GOTIFY_DATABASE_DIALECT=sqlite3
        #- GOTIFY_DATABASE_CONNECTION=gotify.db
        - GOTIFY_DEFAULTUSER_NAME=${USERNAME}
        - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_PASSWORD}
    networks:
      - backend
    #ports:
      #- 443:443
      #- 80:80
    labels:
      - "traefik.enable=true"
      - "traefik.backend=gotify"
      - "traefik.frontend.rule=Host:gotify.${FQDN}"
      - "traefik.port=80"
      - "traefik.docker.network=backend"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  backend:
    external:
      name: backend
      #run: docker network create --name=backend